language: python
notifications:
  email: none
sudo: required
python:
  - "3.6"

install:
 - sudo apt-get install gfortran libblas-dev liblapack-dev libhdf5-serial-dev netcdf-bin libnetcdf-dev
 - pip install py-cpuinfo
 - pip install -r requirements.txt
 - python setup.py build_ext --inplace
 # - pip install git+https://github.com/AuditoryBiophysicsLab/verhulst-model-core.git@master
# command to run tests

 - python setup.py test
script: python -c "assert 1"
#py.test