language: python
notifications:
  email: none
sudo: required
python:
  - "3.5"

# pre install
# command to install dependencies
install:
 - sudo apt-get install gfortran libblas-dev liblapack-dev
 - pip install py-cpuinfo
 - pip install -r requirements.txt
 # - pip install git+https://github.com/AuditoryBiophysicsLab/verhulst-model-core.git@master
 - python setup.py test
# command to run tests
script: python -c "assert 1"
#py.test