language: python
notifications:
  email: none
sudo: required
python:
  - "3.4"
  - "3.5"

# pre install
# command to install dependencies
install:
 - sudo apt-get install gfortran libblas-dev liblapack-dev
 - pip install -r requirements.txt
 - python setup.py install
# command to run tests
script: py.test