name: thesis-code
dependencies:
  - python>=3.4
  - pip
  - pip:
      - blessed >= 1.14
      - progressbar2 >= 3.6
  - docopt >= 0.6.2
  - matplotlib >= 1.5.1
  - numpy >= 1.10
  - scipy >= 0.17.0
  - PyYAML >= 3.11
